### ISSUE TITLE
Suggestion for supportsAllChains

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [wujunchuan/ual-meetone#1]
If MEET.ONE only supports the EOS Mainnet chain, then I would recommend to check the supportedChains in the same way the ual-lynx Authenticator does.

See here: https://github.com/EOSIO/ual-lynx/blob/master/src/Lynx.ts#L54

https://github.com/meet-one/ual-meetone/blob/59d01e595c5b60d0f64b90a40b06ef1291ecffdf/src/MeetOne.ts#L41

**Comment by wuyahuang** [comment]
Hello, Jeff, thanks for your reply, already updated.
https://github.com/meet-one/ual-meetone/commit/ea760da7170efd2f7fb2e9512b07f6a255e1ccc4

**Comment by jeffreyssmith2nd** [comment]
You'll also need to define the supportedChains object.

https://github.com/EOSIO/ual-lynx/blob/master/src/Lynx.ts#L25

**Comment by wuyahuang** [comment]
😄 my mistake, updated.
https://github.com/meet-one/ual-meetone/commit/94fc6e306cb1eccead75535e24e0434e914dafe3
