### ISSUE TITLE
Failure to Render

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [wujunchuan/ual-meetone#2]
In a small test app, the Meet one button does not render because of the isMeetOneReady check. This is due to the Scatter check. I think the right check would be to use the Bridge to see if the meet one app is available rather than checking for scatter.

https://github.com/meet-one/ual-meetone/blob/59d01e595c5b60d0f64b90a40b06ef1291ecffdf/src/MeetOne.ts#L31

**Comment by wuyahuang** [comment]
Hello, Jeff, thanks for your reply, MEET.ONE wallet is integrated with Scatter javascript protocol, so window.scatter is injected to wallet browser. We have tested it on the wallet, everything is doing well.
Wallet download link: https://m.oheos.com/download/?source=cpubaole

**Comment by wujunchuan** [comment]
In MEET.ONE wallet client webview, we will inject some code automatically to simulate the scatter actions and cover to our custom Bridge for adapting some existed dApps which support scatter protocol.

We have also defined some special prototypes for example `scatter.isInject=true` and `scatter.wallet='MEETONE'`.So we use `window.scatter.isInject` to check.

So `ual-meetone` **won’t  be rendered  in PC environment** (because we don't support any other platforms except MEET.ONE client webview). 

I am not sure invoke `render` in some unsupported environments and then guide users to download our client is suitable or not 🤣

**Comment by jeffreyssmith2nd** [comment]
The way we tested was:
1. Cloned this repo
2. Did a `yarn install` `yarn build`
3. Used `yarn link` to install it into the [React Example App](https://github.com/EOSIO/ual-reactjs-renderer/tree/master/examples)
4. Updated it to use the MeetOneAuthenticator here https://github.com/EOSIO/ual-reactjs-renderer/blob/94329a4953930e9393c9b36b0116111a1ca49e0b/examples/src/ButtonWebViewReact.tsx#L180
5. Used [ngrok](https://ngrok.com/) so that we could test it in the Meet One Android app.

Doing all of those steps, it didn't render. If we hardcoded `isMeetOneReady` to return `true`, it rendered and allowed us to login.

Is there a way to pull logs from the app? Happy to send logs if there is.

**Comment by wujunchuan** [comment]
@jeffreyssmith2nd 
Hey, Jeff.

We have updated the React Example App in pr #3 .

**Comment by jeffreyssmith2nd** [comment]
This is what I get when running the example you added in the latest Android app.

![Screenshot_20190404-110150](https://user-images.githubusercontent.com/26460069/55566238-48204380-56c9-11e9-9761-523eca7b7dbc.png)
![Screenshot_20190404-110156](https://user-images.githubusercontent.com/26460069/55566239-48204380-56c9-11e9-93f9-8d211f9e10bf.png)

**Comment by wujunchuan** [comment]
Hey, can you tell me the client version? I work well in my Android platform
 
![image](https://user-images.githubusercontent.com/7511631/55569672-8ef75300-5734-11e9-99ee-65eb9566c768.png)
![image](https://user-images.githubusercontent.com/7511631/55569681-91f24380-5734-11e9-91c3-dc86d8e618e9.png)
![image](https://user-images.githubusercontent.com/7511631/55569688-94549d80-5734-11e9-947a-f8552840bdd2.png)

**Comment by jeffreyssmith2nd** [comment]
The about section says I'm running 2.3.0

**Comment by wujunchuan** [comment]
http://e48b60a2.ngrok.io/
I use ngrok for mapping demo to the Net, Can you try it again?

**Comment by jeffreyssmith2nd** [comment]
Yeah that worked for me, so I'm not sure what's wrong on my end. Glad to see it working though!

**Comment by wujunchuan** [comment]
Aha. I don't do anything works. Just use the  examples about `reactjs-renderer`

https://github.com/meet-one/ual-meetone/tree/master/examples/reactjs-renderer

If you wan't to test somethings. you can download the zip file,

and then run `npx http-server -p 80`

Sleepy, sleep first. 🌙 

[build.zip](https://github.com/meet-one/ual-meetone/files/3044470/build.zip)

**Comment by wuyahuang** [comment]
@jeffreyssmith2nd Hello, Jeff, are we good to push ual-meetone to [universal-authenticator-library](https://github.com/EOSIO/universal-authenticator-library) right now?
